// dom.ts - Production-Ready High-Performance DOM Factory for Levelo JS

/**
 * Global reactive tracking context inspired by SolidJS.
 * Helps cleanly wipe out memory scales and effects during dynamic route swap cycles.
 */

import { effect } from './reactivity/index.js';
//export let activeOwner: any = null;

//export function setOwner(owner: any): void {
  //activeOwner = owner;
//}

const SVG_NS = "http://www.w3.org/2000/svg";
const MATH_NS = "http://www.w3.org/1998/Math/MathML";

export type TagType = string | ((props: any) => Element);
type lastAnchorType = Comment | Element;

/**
 * HyperScript Factory (h) - Translates Levelo JSX into highly optimized browser nodes.
 * Supports static values, dynamic getter attributes, and functional text nodes.
 */
export function h(tag: TagType, props: Record<string, any> | null, ...children: any[]): Element {
  const safeProps: Record<string, any> = props || {};
  let element: Element;
  
  // Seamlessly normalize 'className' to 'class' for React ecosystem compatibility
  if ('className' in safeProps) {
    const descriptor = Object.getOwnPropertyDescriptor(safeProps, 'className');
    if (descriptor) {
      Object.defineProperty(safeProps, 'class', descriptor);
    } else {
      safeProps.class = safeProps.className;
    }
    delete safeProps.className;
  }


  // Component Resolution Layer (<Pages />, <Page />, <HomePage />)
  if (typeof tag === 'function') {
    safeProps.children = children.length === 1 ? children[0] : children;
    return tag(safeProps);
  }
  
  const namespace =
    safeProps.__namespace ||
    (tag === 'svg' ? SVG_NS :
    tag === 'math' ? MATH_NS :
    null);

  if (namespace) {
    element = document.createElementNS(namespace, tag);
  } else {
    element = document.createElement(tag);
  }


  // Smart Attribute & Property Mapping
  Object.entries(safeProps).forEach(([key, value]) => {
    if (key === 'children') return;

    let targetKey = key;

    if (key === "render-string") {
      element.innerHTML = String(value);
      return;
    }

    // Intercept and Track Event Listeners (e.g., onclick)
    if (targetKey.startsWith('on') && typeof value === 'function') {
      const eventName = targetKey.toLowerCase().substring(2);
      element.addEventListener(eventName, value);
      return;
    }
    if (namespace === SVG_NS) {

      const camelCaseExceptions = ['viewBox', 'gradientTransform', 'gradientUnits', 'patternUnits'];

      if (camelCaseExceptions.includes(targetKey)) {
        // // targetKey will remain as it is (e.g., 'viewBox')
      } else {
        targetKey = targetKey.replace(/([A-Z])/g, "-$1").toLowerCase();
      }
      
    }
    // Handle Static or Reactive Style Objects
    if (targetKey === 'style' && value !== null) {
      const descriptor = Object.getOwnPropertyDescriptor(safeProps, key);
      const htmlElement = element as HTMLElement | SVGElement;
      if (descriptor && descriptor.get) {
        // Reactive style
        effect(() => {
          const styleVal = safeProps[key];
          if (typeof styleVal === 'object') {
            Object.assign(htmlElement.style, styleVal);
          } else if (typeof styleVal === 'string') {
            htmlElement.style.cssText = styleVal;
          }
        });
      } else if (typeof value === 'object') {
        // Static style
        Object.assign(htmlElement.style, value);
      }
    }
    // Handle Dynamic Getters / Properties
    else {
      // If the property has a JavaScript 'getter' descriptor, it's a dynamic reactive property
      const descriptor = Object.getOwnPropertyDescriptor(safeProps, key);
      if (descriptor && descriptor.get) {
        // We defer this execution to the Reactivity Layer (Layer 3)
        effect(() => {
          let val = safeProps[key];
          if (typeof val === 'function') val = val();
          if (val !== false && val !== null && val !== undefined) {
            element.setAttribute(targetKey, String(val));
          }
        });
      } else {
        if (value !== false && value !== null && value !== undefined) {
          element.setAttribute(targetKey, String(value));
        }
      }
    }
  });

  // Recursive Children Processing Injection System
  const processChildNode = (child: any, parentNamespace: string | null = null) => {
    if (child === null || child === undefined || child === false) return;

    // If child is an arrow function wrapper -> () => count() (Generated by our Compiler)
    if (typeof child === 'function') {
      const anchor = document.createComment('levelo-dynamic');
      element.appendChild(anchor);
      let currentNodes: (Element | Text)[] = [];

      effect(() => {
        const res = child();
        //remove old nodes
        currentNodes.forEach(n => n.remove());
        currentNodes = [];

        if (res === null || res === undefined || res === false) return;

        // if the return value is directly an Element (such as SVG or DIV)
        if (res instanceof Element) {
          anchor.after(res);
          currentNodes=[res];
        }
        
        // if the return value is a Arry/List
        else if (Array.isArray(res)) {
          let lastAnchor: lastAnchorType = anchor;
          res.forEach(item => {
            if (item === null || item === undefined || item === false) return;
            let nodeToInsert: Element | Text;
            if (item instanceof Element) {
              nodeToInsert = item;
            } else {
              nodeToInsert = document.createTextNode(String(item));
            }
            lastAnchor.after(nodeToInsert);
            lastAnchor = nodeToInsert;
            currentNodes.push(nodeToInsert);
          });
        }

        // if the return value is a Primitive (string, number)
        else {
          const t = document.createTextNode(String(res));
          anchor.after(t);
          currentNodes = [t];
        }
      });
    }

    // If child is a nested Element node
    else if (child instanceof Element) {
      element.appendChild(child)
    }
    // If children are nested arrays
    else if (Array.isArray(child)) {
      child.forEach(item => {
        processChildNode(item, parentNamespace);
      });
    }
    // Regular Static Primitive Fallbacks (Strings, Numbers)
    else {
      element.appendChild(document.createTextNode(String(child)));
    }
  };

  children.forEach(child => {
    processChildNode(child, namespace);
  });

  return element;
}

/**
 * Standard Application Target Mounting Entry Root Runtime.
 */
export function render(rootComponent: () => any, container: HTMLElement | null): void {
  if (!container) return console.error('[Levelo] Dom injection target container missing.');
  container.innerHTML = '';
  
  const rootInstance = rootComponent();
  if (rootInstance instanceof Element) {
    container.appendChild(rootInstance);
  }
}
